title: Sun
author: GitHub User
email: rigt@example.com
description: >  
This is about the Sun.

# social links
github_username:  rigt # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: modernist
